// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WK_Services.Infrastructure.Presistence.Context;

#nullable disable

namespace WK_Services.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WK_Services.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shipment_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Cairo",
                            Country = "Egypt",
                            Email = "info@client1.com",
                            Name = "client1",
                            Phone = "01000000001",
                            Shipment_Address = "Address 1"
                        },
                        new
                        {
                            Id = 2,
                            City = "Giza",
                            Country = "Egypt",
                            Email = "info@client2.com",
                            Name = "client2",
                            Phone = "01000000002",
                            Shipment_Address = "Address 2"
                        });
                });

            modelBuilder.Entity("WK_Services.Domain.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("User_Name")
                        .IsUnique();

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            Email = "ahmed@client1.com",
                            Mobile = "01005500111",
                            Name = "ahmed",
                            Password = "GSEv3AiHWIvYxmVU39ZAzzO5S3HYyaHK9uOTYWD18pI=",
                            User_Name = "contact1_1"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            Email = "sara@client2.com",
                            Mobile = "01005500222",
                            Name = "sara",
                            Password = "GSEv3AiHWIvYxmVU39ZAzzO5S3HYyaHK9uOTYWD18pI=",
                            User_Name = "contact2_1"
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 2,
                            Email = "mona@client2.com",
                            Mobile = "01005500333",
                            Name = "mona",
                            Password = "GSEv3AiHWIvYxmVU39ZAzzO5S3HYyaHK9uOTYWD18pI=",
                            User_Name = "contact2_2"
                        });
                });

            modelBuilder.Entity("WK_Services.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByContactId")
                        .HasColumnType("int");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RequestedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedByContactId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("ServiceId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WK_Services.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Air Mail service - sample description.",
                            Name = "AM"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Land Line service - sample description.",
                            Name = "LL"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fast Box service - sample description.",
                            Name = "FB"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Legacy Land Line service - sample description.",
                            Name = "Old LL"
                        });
                });

            modelBuilder.Entity("WK_Services.Domain.Entities.Contact", b =>
                {
                    b.HasOne("WK_Services.Domain.Entities.Client", "Client")
                        .WithMany("Contacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WK_Services.Domain.Entities.Order", b =>
                {
                    b.HasOne("WK_Services.Domain.Entities.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WK_Services.Domain.Entities.Contact", "CreatedByContact")
                        .WithMany("Orders")
                        .HasForeignKey("CreatedByContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WK_Services.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("CreatedByContact");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("WK_Services.Domain.Entities.Client", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WK_Services.Domain.Entities.Contact", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
